### ISSUE TITLE
Include damaged lines in the observation

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/PyPowNet#16]
We should include a new part to our observation : the damaged lines.
The underlying idea is that an agent should be able to retrieve the reward from what it observes

**Comment by MarvinLer** [comment]
Damaged line can be assessed since d945e4c using Observation.timesteps_before_lines_reconnectable > 0 which produces an array of boolean, with True meaning that the line is damaged, so not reconnectable.
Note: damaged lines are not used in the reward computation atm (except for their capacity usage, which is not specific to damaged lines)
