### ISSUE TITLE
gym compatibility

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#28]
There are a few modifications that could be made so as to improve the compatibility with the openai.gym framework. More specifically, I tried to directly implement a dqn agent developed to work on gym problems, and I observed the following errors:

1/ 'ObservationSpace' object has no attribute 'shape'
        This is not the same as the arrribute env.observation_space.grid_number_of_elements! The shape attribute is simply not defined

2/ AttributeError: 'ActionSpace' object has no attribute 'n'
	
3/ AttributeError: 'ActionSpace' object has no attribute 'sample'

4/ new_state, reward, is_done, _ = self.env.step(action)
One needs to convert new_state to an array using new_state.as_array(), while in the gym framework it is directly an array

I'll add some comments if I find some other compatibility issue

**Comment by MarvinLer** [comment]
1, 2 and 3 are fixed in 01869b16594e053b285dbfc5bcb5edf487f3a67c. The action and observation spaces are now coded with the gym framework (gym.spaces) to be more robust and scalable wrt the gym framework. Also consequently the gym dependency on the projet is now mandatory.

Will need additional work for the last point about returning numpy arrays as observation.

Please tell me if you find any bug with the new update.

**Comment by MarvinLer** [comment]
Since commit 83906b4baf0688d311e643d47606a9daea08d122, observations given by the environment are numpy arrays, and agents can produce numpy arrays or objects Action as output. For models with grid conduct insight (eg differentiate activations of line status switch or node splitting), the function observation_space.array_to_observation converts a numpy array into its equivalent Observation.

The agents have been updated concordingly, particularly for the tree search ones. Some models need to explicitely convert the given observation (np array) into an Observation to perform more precise activations.
Also, there is a new _simple_ agent that produce a 1-activation action, ie 1 line switch or 1 node splitting, to illustrate the use of an agent with only numpy.

Closing the issue, please reopen if there is any issue related to this!
