### ISSUE TITLE
simulate

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#3]
This function should be deleted from env.py (because the frame by frame approach makes it useless)
However we still need it for developing purposes for at least a few weeks

**Comment by MarvinLer** [comment]
Simulate is broken atm, working on it this afternoon.

**Comment by MarvinLer** [comment]
As of b2193302afa2a9ad196e5c54b5e6ad6ada34d132, the simulate method differs from the step method in three ways:
- simulate uses the DC mode for loadflow computation (while the step used AC)
- simulate uses the injections predictions given to the current timestep as the next timestep injections, instead of the realized injections of the next timestep; consequently, the simulate method does not see the next timestep injections
- simulate does not compute the hazards that are supposed to happen at the next timestep (given by chronics); it still computes the next timestep maintenance, as they are given in an observation

With those three points, the simulate method acts as a simulator within the simulator (simpler electrical model + uses only predictions for next timestep entries), so there is no reason to hide it anymore.
