### ISSUE TITLE
Confusing get_switches_configuration_of_substation(*args) behaviour

### ISSUE THREAD

**Issue by camiloromers** [MarvinLer/pypownet#31]
The method you have called get_switches_configuration_of_substation(*args) which takes as arguments the _action_ and the _substation_id_ is a bit confusing sometimes. Personally I think this method should give you the current switches status of the grid independently of the action you're taking because you are only interested to know how elements are connected in the grid. By default all belongs the busbar 0 but when you make some changes, you want to know how the grid looks like now and if you pass the incorrect action array, the information you get is misleading.

**Comment by MarvinLer** [comment]
Actually the method you are referring to is part of the class `pypownet.environment.ActionSpace` which deals with actions and not observations. This function return the values of the switches of a substation as they are in the function input action (so not related to observation): this is intended to understand the actions of an agent, by looking at its actions with a grid conduct point of view. Ideally this method should be part of the class `Action`, however since actions can be np arrays the class is inherently limited so these kind of functions have been exported to the action space.

For observation analysis, there is a function `get_nodes_of_substation` inside the `pypownet.environment.Observation` class which retrieves the self values of the nodes of the input substation (see docstring for details). Since 1f0d1a90133b2f5089074aae6fbefacf2b67320c there is also its equivalent `get_lines_status_of_substation` about lines status, ie retrieves the lines status (in the observation self).
There is more info in the [documentation](https://pypownet.readthedocs.io/en/latest/).
