### ISSUE TITLE
TO DO before competition Starts

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#38]
1) Fix Ampere Issue
2) Add soft mode with no line disconnections
3) Visualize in the renderer the number of nodes at substations

**Comment by MarvinLer** [comment]
1. is fixed in 5bf69f2aa1f73f22efc51101251dbfb6c59d22f2.

**Comment by MarvinLer** [comment]
3. is done in d98ef7741a0cabd3a662823964857d7b84b9dc60. Legend will need to be updated for completeness; future versions will update the renderer overall.

**Comment by MarvinLer** [comment]
Feature 2. added in 6e2c1844fd3541996ea5a1ec699f9f873f1b49d3.
In any parameters environment and independently from them, the cli aurgment `--no-overflow-cutoff` will toggle OFF the simulator mechanism that cut-off the lines was above their capacity (hard overflows) or overflowed lines for too much consecutive timesteps (soft overflows). Please note that with this mode remains some game over, including the ones due to connexity errors, or due to excess number of prods/loads isolated from the main island.

Also added in this commit some logs which display in normal mode the automatic cut-off lines eg:
![image](https://user-images.githubusercontent.com/14179877/57193924-d5f98380-6f40-11e9-9859-b0df145ee12c.png)
