### ISSUE TITLE
Score & reward are intermixed - give access to observation in simulate

### ISSUE THREAD

**Issue by marota** [MarvinLer/pypownet#46]
If participants don't use machine learning but optimization based on simulate and its rewards, when they will submit on the codalab competition, the simulation reward will be the one of our score in reward.py.
To let them compute their own reward when submitting, we can give them the observation as an output of simulate in environment.py, as in game.py. Then they will be able to recompute a local reward. 
Modifications of the agents using simulate API will need to be updated after this change.

**Comment by MarvinLer** [comment]
From ca5e9336d1aca7a6f0d9aa7cd261ed4a0b95e427, the simulate API of class RunEnv is the same as the one of step ie returns tuple _(observation, reward, info, done)_; the previsions inside the returned observation are the same as the previsions inside the current observation so that no additional information about the future is given to users of simulate.
