### ISSUE TITLE
Frame by frame approach

### ISSUE THREAD

**Issue by bdonon** [MarvinLer/pypownet#6]
Disable the intermediate time step "t+0.5", and follow this process:

1/ Apply action + apply new injections
2/ Perform load flow + cascading failure

safe mode :
3/ If the cascading failure results in a stable situation and there is no game over condition satisfied, then do nothing. Return the corresponding reward, etc
    Else, cancel action and return low reward

hardcore mode:
3/ If the cascading failure results in a stable situation and there is no game over condition satisfied, then do nothing. Return the corresponding reward, etc
    Else, return game over

**Comment by MarvinLer** [comment]
Swapped from curative mode to preventive mode in edbc88f.
The process at each timestep is:
* apply the action on the grid (node splitting + line service status switches off)
* load the next set of injections
* perform a first loadflow computation
* perform a cascading failure simulation

The step function has been moved to the module pypownet.game, and its process is now supposed to be hidden to the env users. Also, the rewards is now much simpler: any loadflow error is raised, including a game over.

Not closing the ticket since in the process of second part of request i.e. safe/hardcore modes.

**Comment by MarvinLer** [comment]
This has been implement several commits ago. Hard mode will end the current chronic and play the next one; soft mode will load next timestep of same chronic. See ``python -m pypownet.main --help``.
